### ISSUE TITLE
Path to python problematic on some systems

### ISSUE THREAD

**Issue by sogaiu** [pesterhazy/zprint-mode.el#6]
First, thanks for zprint-mode :)

I had some trouble getting it to work initially -- it looks like there is an expectation of python2 being used.  Is that right?

For whatever reasons, the system I'm using treats `python` as `python3`.  Changing the instance of `python` in the following bit to `python2` seems to work for me:

```
$(python -c \"import sys,hashlib; m=hashlib.sha256(); f=open(sys.argv[1]) if len(sys.argv)>1 else sys.stdin; m.update(f.read()); print(m.hexdigest())\" \"$our_temp_dir/zprint\")\";
```

This seems consistent with:

> We expect Unix-like software distributions (including systems like macOS and Cygwin) to install the python2 command into the default path whenever a version of the Python 2 interpreter is installed, and the same for python3 and the Python 3 interpreter

via: https://www.python.org/dev/peps/pep-0394/#for-python-runtime-distributors

Do you think changing the code to reference `python2` would be reasonable?

**Comment by pesterhazy** [comment]
Thanks for the report. Should be fixed in 0.2
